/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Exercise {
  'difficulty' : bigint,
  'name' : string,
  'description' : string,
  'muscleGroup' : string,
}
export interface LogEntry {
  'actualExercises' : Array<WorkoutExercise>,
  'time' : Time,
  'workoutPlanId' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'weight' : bigint,
  'height' : bigint,
  'fitnessGoal' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkoutExercise {
  'weight' : bigint,
  'exerciseId' : bigint,
  'reps' : bigint,
  'sets' : bigint,
}
export interface WorkoutPlan {
  'name' : string,
  'exercises' : Array<WorkoutExercise>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExercise' : ActorMethod<[Exercise], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createWorkoutPlan' : ActorMethod<[WorkoutPlan], bigint>,
  'getAllExercises' : ActorMethod<[], Array<Exercise>>,
  'getAllWorkoutPlans' : ActorMethod<[], Array<WorkoutPlan>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCallerWorkoutHistory' : ActorMethod<[], Array<LogEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkoutHistory' : ActorMethod<[Principal], Array<LogEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logWorkout' : ActorMethod<[LogEntry], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];