/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Exercise = IDL.Record({
  'difficulty' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'muscleGroup' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WorkoutExercise = IDL.Record({
  'weight' : IDL.Nat,
  'exerciseId' : IDL.Nat,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
});
export const WorkoutPlan = IDL.Record({
  'name' : IDL.Text,
  'exercises' : IDL.Vec(WorkoutExercise),
});
export const UserProfile = IDL.Record({
  'weight' : IDL.Nat,
  'height' : IDL.Nat,
  'fitnessGoal' : IDL.Text,
});
export const Time = IDL.Int;
export const LogEntry = IDL.Record({
  'actualExercises' : IDL.Vec(WorkoutExercise),
  'time' : Time,
  'workoutPlanId' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExercise' : IDL.Func([Exercise], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createWorkoutPlan' : IDL.Func([WorkoutPlan], [IDL.Nat], []),
  'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
  'getAllWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerWorkoutHistory' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkoutHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LogEntry)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWorkout' : IDL.Func([LogEntry], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Exercise = IDL.Record({
    'difficulty' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'muscleGroup' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WorkoutExercise = IDL.Record({
    'weight' : IDL.Nat,
    'exerciseId' : IDL.Nat,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
  });
  const WorkoutPlan = IDL.Record({
    'name' : IDL.Text,
    'exercises' : IDL.Vec(WorkoutExercise),
  });
  const UserProfile = IDL.Record({
    'weight' : IDL.Nat,
    'height' : IDL.Nat,
    'fitnessGoal' : IDL.Text,
  });
  const Time = IDL.Int;
  const LogEntry = IDL.Record({
    'actualExercises' : IDL.Vec(WorkoutExercise),
    'time' : Time,
    'workoutPlanId' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExercise' : IDL.Func([Exercise], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createWorkoutPlan' : IDL.Func([WorkoutPlan], [IDL.Nat], []),
    'getAllExercises' : IDL.Func([], [IDL.Vec(Exercise)], ['query']),
    'getAllWorkoutPlans' : IDL.Func([], [IDL.Vec(WorkoutPlan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerWorkoutHistory' : IDL.Func([], [IDL.Vec(LogEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkoutHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LogEntry)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWorkout' : IDL.Func([LogEntry], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };